### ISSUE TITLE
Igorw\FileServeBundle\Response\AbstractResponseFactory::create is not readable.

### ISSUE THREAD

**Issue by ghost** [igorw/IgorwFileServeBundle#15] opened 2014-02-17 18:49 UTC
The directory is already created, I have it in: /app/upload. But it rises the error. What permissions should I check in order to getting it functional?

**Comment by igorw** [comment] 2014-02-18 09:13
What is the actual error message?

**Comment by skypeter1** [comment] 2014-05-01 03:50
I have this error to, my message is Provided filename 'C:/wamp/www/Gestor/app/uploads/documents' for Igorw\FileServeBundle\Response\AbstractResponseFactory::create is not readable.  Why is this?

**Comment by igorw** [comment] 2014-07-06 11:02
The file needs to be readable by the user that the PHP process is running under. Closing as not a bug.

**Closed as completed by igorw** 2014-07-06 11:02 UTC
